// Generated by CoffeeScript 1.6.3
var app, exports, express, fs, port;

express = require("express");

fs = require("fs");

require('coffee-script');

app = express();

app.configure(function() {
  app.use(express.bodyParser());
  app.use(express["static"](__dirname + "/public"));
  app.use(app.router);
  app.set("views", __dirname + "/views");
  return app.set("view engine", "jade");
});

app.use(express.logger());

port = process.env.PORT || 5000;

app.listen(port, function() {
  return console.log("Listening on " + port);
});

app.get('/', function(req, res) {
  return res.render('index');
});

exports = module.exports = app;
