// Generated by CoffeeScript 1.6.3
var app, coffee, currentPicture, exports, express, fs, http, io, port, server;

fs = require("fs");

http = require("http");

coffee = require('coffee-script');

express = require("express");

app = express();

port = process.env.PORT || 5000;

server = app.listen(port, function() {
  return console.log("Listening on " + port);
});

io = require("socket.io").listen(server);

app.configure(function() {
  app.use(express.bodyParser());
  app.use(express["static"](__dirname + "/public"));
  app.use(app.router);
  app.use(express.favicon());
  app.set("views", __dirname + "/views");
  return app.set("view engine", "jade");
});

app.use(express.logger());

app.get('/', function(req, res) {
  return res.render('index');
});

currentPicture = '';

setInterval((function() {
  return io.sockets.emit('pictureFromServer', currentPicture);
}), 1000.);

io.sockets.on('connection', function(socket) {
  io.sockets.emit('newChatter');
  socket.on('messageText', function(data) {
    socket.emit('messageFromServer', data);
    socket.broadcast.emit('messageFromServer', data);
    return console.log(data);
  });
  return socket.on('picture', function(data) {
    currentPicture = data;
    socket.emit('pictureFromServer', data);
    socket.broadcast.emit('pictureFromServer', data);
    return console.log(data);
  });
});

exports = module.exports = app;
